# SPDX-FileCopyrightText: 2025 Siemens AG
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = ["**.md", "model/base.go", ".markdownlint.json"]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["specs/*.proto", "generated/**.go"]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "renovate.json",
  "registry/Dockerfile",
  "Dockerfile",
  ".github/*",
  "**.editorconfig",
  "**/go.mod",
  "**/go.sum",
  "docs/images/favicon.ico",
  "cdm-al-reference/simdevices/static/index.html",
  "misc/device-identifier.json",
  "misc/discovery.json",
  "misc/registry.json",
  "misc/simulated_device_firmware_*.fwu",
  "cookiecutter-project-template/{{ cookiecutter.al_project }}/.markdownlintrc",
  "cookiecutter-project-template/{{ cookiecutter.al_project }}/go.mod.tmpl",
  "cookiecutter-project-template/*.json",
]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "model/cdm_base.schema*.json"
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"
