# SPDX-FileCopyrightText: 2023 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0


version = 1

[[annotations]]
path = ["**.md", "model/base.go"]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["specs/*.proto", "generated/**.go"]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "renovate.json",
  "Dockerfile",
  "**.editorconfig",
  "**/go.mod",
  "**/go.sum",
  "cookiecutter-project-template/{{ cookiecutter.al_id }}/.markdownlintrc",
  "cookiecutter-project-template/{{ cookiecutter.al_id }}/go.mod.tmpl",
  "cookiecutter-project-template/*.json",
]
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = "model/cdm_base.schema*.json"
SPDX-FileCopyrightText = "2024 Siemens AG"
SPDX-License-Identifier = "Apache-2.0"
